out.path = "/tmp/example.xml"
bias = 0.2

[img]
sunrise = "sunrise-path"
noon = "noon-path"
sunset = "sunset-path"
evening = "evening-path"
midnight = "midnight-path"

[loc]
latitude = 50.0
longitude = 25.0
